### ISSUE TITLE
AR Blue Cross Actions Workshop: Mar 6-7, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/arkensas-blue-cross#1]
Leave the comment with the following information:

- First Name/Last Name
- Role/Title
- Business Email Address

**Comment by RinatS** [comment]
Rinat Shagisultanov
Technical Director
rinats@infomagnus.com

**Comment by rsharma2023** [comment]
Rajan Sharma
Technical Architect
rsharma@arkbluecross.com

**Comment by MXRAMIREDDY** [comment]
Manohara Reddy Ramireddy
Sr, Developer
mxramireddy@arkbluecross.com

**Comment by aptaucher** [comment]
Paul Taucher
GitHub Admin
aptaucher@arkbluecross.com

**Comment by jordanstock** [comment]
Jordan Stock 
Developer 
jastock@arkbluecross.com

**Comment by SriPatlaola** [comment]
Srikanth Patlaola
Developer
sxpatlaola@arkbluecross.com

**Comment by ChrisMcQuay** [comment]
Chris McQuay
Developer Senior
clmcquay@arkbluecross.com

**Comment by rayatesabcbs** [comment]
Aaron Yates
Supervisor - Enterprise and Point Solution APIs
rayates@arkbluecross.com

**Comment by RinatS** [comment]
Completed
