### ISSUE TITLE
AR Blue Cross Actions Workshop: Mar 8-9, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/arkensas-blue-cross#2]
Leave the comment with the following information:

- First Name/Last Name
- Role/Title
- Business Email Address

**Comment by RinatS** [comment]
Leave the comment with the following information:

- First Name/Last Name
- Role/Title
- Business Email Address

**Comment by RinatS** [comment]
Rinat Shagisultanov
Tech Director
rinats@infomagnus.com

**Comment by jpjones2** [comment]
Jon Paul Jones
Developer Lead
jpjones@arkbluecross.com

**Comment by WendellBrown** [comment]
Wendell Brown
Supervisor Integration Hub & Core Data
wkbrown@arkbluecross.com

**Comment by taharasym** [comment]
Tim Harasym
Kafka/Java Lead
taharasym@arkbluecross.com

**Comment by sandipwish** [comment]
Sandip Shaw
Senior Developer
sxshaw@arkbluecross.com

**Comment by blbrecheisen** [comment]
Brice Brecheisen
Developer
blbrecheisen@arkbluecross.com

**Comment by gwfox2005** [comment]
Greg Fox
Supervisor
gwfox@arkbluecross.com

**Comment by bryanthog94** [comment]
Brian Terry
Software Admin
bcterry@arkbluecross.com

**Comment by affan66020** [comment]
Affan Mohammed
Developer
axmohammed1@arkbluecross.com

**Comment by lepinzone** [comment]
Luis Pinzon
Developer
lepinzon@arkbluecross.com

**Comment by BGuryev** [comment]
Boris Guryev
Developer
bvguryev@arkbluecross.com
