### ISSUE TITLE
AR Blue Cross Workflow Workshop: Mar 14, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/arkensas-blue-cross#3]
Leave the comment with the following information:

- First Name/Last Name
- Role/Title
- Business Email Address

**Comment by rsharma2023** [comment]
Rajan Sharma
Tech Architect
rsharma@arkbluecross.com

**Comment by RinatS** [comment]
Rinat Shagisutanov
Tech Director
rinat.shsgisultanov@infomagnus.com

**Comment by jordanstock** [comment]
Jordan Stock 
Developer 
jastock@arkbluecross.com

**Comment by SriPatlaola** [comment]
srikanth patlaola
Developer
sxpatlaola@arkbluecross.com

**Comment by WendellBrown** [comment]
Wendell Brown
Supervisor Integration Hub & Core Data
wkbrown@arkbluecross.com

**Comment by MXRAMIREDDY** [comment]
Manohara R Ramireddy
Sr. Developer
mramireddy@arkbluecross.com

**Comment by returnerabcbs** [comment]
Robert Turner
Supervisor
returner@arkbluecross.com
